### ISSUE TITLE
-bash: build: command not found

### ISSUE THREAD

**Issue by wSedlacek** [Pavo-IM/AptioMemFix#2]
What package needs to be installed for the build command? I am on MacOS 10.12.6

**Comment by wSedlacek** [comment]
The build command wasn't compiling because one of the test in the compiling was failing from the UDK2017 version, went to UDK2018 and it compiled but I am getting this error when building.

clang: error: unknown argument: '-maccumulate-outgoing-args'

I searched the entire project for "-maccumulate-outgoing-args" and only found it in tools_def.template, I removed it and recompiled but I am still getting the same error.

**Comment by wSedlacek** [comment]
Build log:
https://hastebin.com/uriyezuzev.sql

**Comment by Pavo-IM** [comment]
Nothing is required on your end to compile, everything is done inside the docker container. All you need is Docker for Mac installed.

**Comment by Pavo-IM** [comment]
Added README with instructions.
